steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/heroic-footing-460117-k8/github.com/nquinn721/grantaccount:$COMMIT_SHA',
        '.',
      ]
